import { PokerSession } from '@planning-poker/shared';

/**
 * Action types
 */
export enum PokerActionTypes {
    START_POKER_REQUEST = 'START_POKER_REQUEST',
    START_POKER_SUCCESS = 'START_POKER_SUCCESS',
    START_POKER_FAILURE = 'START_POKER_FAILURE',

    STOP_POKER_NOT_ENOUGH_PLAYERS = 'STOP_POKER_NOT_ENOUGH_PLAYERS',

    SET_TASK_DESCRIPTION_REQUEST = 'SET_TASK_DESCRIPTION_REQUEST',
    SET_TASK_DESCRIPTION_SUCCESS = 'SET_TASK_DESCRIPTION_SUCCESS',
    SET_TASK_DESCRIPTION_FAILURE = 'SET_TASK_DESCRIPTION_FAILURE',

    SELECT_CARD_VALUE_REQUEST = 'SELECT_CARD_VALUE_REQUEST',
    SELECT_CARD_VALUE_SUCCESS = 'SELECT_CARD_VALUE_SUCCESS',
    SELECT_CARD_VALUE_FAILURE = 'SELECT_CARD_VALUE_FAILURE',
    OTHER_PLAYERS_CARD_VALUES = 'OTHER_PLAYERS_CARD_VALUES',

    RESTART_POKER_REQUEST = 'RESTART_POKER_REQUEST',
    RESTART_POKER_SUCCESS = 'RESTART_POKER_SUCCESS',
}

/**
 * Reducer state interface
 */
export type PokerReducerState = PokerSession;
